### ISSUE TITLE
Note on the README

### ISSUE THREAD

**Issue by vsimkus** [initinfosec/joplin-debian#2]
Thanks for doing this, I think it's well-desired by quite a few Joplin users.

I have a small note on the following paragraph in the README:

> Now, an option to run without the sandbox is presented upon failure to launch, stating you can use the --no-sandbox flag. However, upon trying to use that option, A UI window appears and says: "Unrecognized flag --no-sandbox." Once this is closed, the application does not launch either. Thus, the prompt for the no-sandbox option was likely from the chromium code itself, whereas the current Joplin build does not have that option implemented, or has disallowed that.

The new Joplin release allows the users to optionally specify the `--no-sandbox` flag, so the above paragraph is not correct.

**Comment by initinfosec** [comment]
Thank you for the note @vsimkus - I had seen that ability so was wondering if that was an intentional change upstream by the Joplin devs -I will update the readme with the next build to reflect that, thanks.
